[package]
name = "aether-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "just-music"
path = "src/main.rs"

[dependencies]
aether-core.workspace = true
aether-audio.workspace = true
aether-cache.workspace = true
aether-monitor.workspace = true
aether-ui.workspace = true
slint.workspace = true
tokio = { version = "1.38", features = ["rt-multi-thread", "macros"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
chrono = { version = "0.4.38", default-features = false, features = ["clock", "std"] }
dirs-next = "2.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_UI_WindowsAndMessaging", "Win32_UI_Shell"] }

[build-dependencies]
winres = "0.1"
