[package]
name = "aether-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "just-music"
path = "src/main.rs"

[dependencies]
aether-core.workspace = true
aether-audio.workspace = true
aether-cache.workspace = true
aether-monitor.workspace = true
aether-ui.workspace = true
eframe.workspace = true
egui.workspace = true
image = { version = "0.25", default-features = false, features = ["ico", "png"] }
tokio = { version = "1.38", features = ["rt-multi-thread", "macros"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
